baseURL = 'https://rococcoon.xyz'
languageCode = 'en-us'
title = "ROCOCCOON"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = false

# Main navigation links
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/blog"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "/projects"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 5
